name: aoc2021-raehik
version: "0.1.0"
extra-source-files:
- README.md

# https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0380-ghc2021.rst#proposed-change
# TODO: GHC2021 should go in default-language but hpack doesn't support yet
default-extensions:
- GHC2021
- LambdaCase
- DerivingStrategies
- NoStarIsType
- DataKinds
- TypeFamilies

dependencies:
- base
- text
- optics
- generic-optics
- mtl
- vector-sized
- finite-typelits
- megaparsec
- parser-combinators

ghc-options:
- -Wall

library:
  source-dirs: src
