name: aoc2021-raehik
version: "0.1.0"
extra-source-files:
- README.md

# all unintrusive extensions from Alexis King's 2018 recommended defaults
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
# plus TypeApplications (useful even without ScopedTypeVariables)
default-extensions:
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- LambdaCase
- DeriveGeneric
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- BangPatterns
- KindSignatures
- TypeOperators
- TypeApplications

dependencies:
- base
- text
- optics
- generic-optics
- mtl

ghc-options:
- -Wall

library:
  source-dirs: src
